// songs/songList.js
const songList = [
    // Clarinet
    { title: "Solo de Concours", file: "Anthony Mcgill - Solo de Concours.mp3", instrument: "clarinet" },
    { title: "Vocalise", file: "Anthony Mcgill - Vocalise.mp3", instrument: "clarinet" },
    { title: "Contrasts- Verbunkos", file: "Béla Bartók, Richard Stoltzman, Richard Goode, Lucy Chapman Stoltzman - Contrasts- Verbunkos.mp3", instrument: "clarinet" },
    { title: "Hommage a Manuel de Falla", file: "Béla Kovács, André Moisan - Hommages- Hommage a Manuel de Falla.mp3", instrument: "clarinet" },
    { title: "After You, Mr. Gershwin!", file: "Béla Kovács, André Moisan, Jean Saulnier - After You, Mr. Gershwin!.mp3", instrument: "clarinet" },
    { title: "Hommage á Aram Khatschaturian", file: "Béla Kovács, Aram Khachaturian, Evgeni Orkin - Hommage á Aram Khatschaturian for Clarinet Solo.mp3", instrument: "clarinet" },
    { title: "Sholem-alekhem, rov Feidman!", file: "Béla Kovács, Todd Levy, Jeannie Yu - Sholem-alekhem, rov Feidman!.mp3", instrument: "clarinet" },
    { title: "Introduction and Variations on a Swedish Song for Clarinet and Orchestra, Op. 12", file: "Bernhard Henrik Crusell, Martin Fröst, Royal Stockholm Philharmonic Orchestra - Introduction and Variations on a Swedish Song for Clarinet and Orchestra, Op. 12.mp3", instrument: "clarinet" },
    { title: "Sonate pour clarinette et piano, Op. 167- I. Allegretto", file: "Camille Saint-Saëns, Pierre Génisson, David Bismuth - Sonate pour clarinette et piano, Op. 167- I. Allegretto.mp3", instrument: "clarinet" },
    { title: "Clarinet Concerto No. 2 in E-Flat Major, Op. 74, J. 118- I. Allegro", file: "Carl Maria von Weber, Martin Fröst, Tapiola Sinfonietta, Jean-Jacques Kantorow - Clarinet Concerto No. 2 in E-Flat Major, Op. 74, J. 118- I. Allegro.mp3", instrument: "clarinet" },
    { title: "Clarinet Concerto No. 2 in E-Flat Major, Op. 74, J. 118- II. Romanza. Andante", file: "Carl Maria von Weber, Martin Fröst, Tapiola Sinfonietta, Jean-Jacques Kantorow - Clarinet Concerto No. 2 in E-Flat Major, Op. 74, J. 118- II. Romanza. Andante.mp3", instrument: "clarinet" },
    { title: "Clarinet Concertino in C Minor", file: "Carl Maria von Weber, Martin Fröst, Tapiola Sinfonietta, Jean-Jacques Kantorow - Concertino for Clarinet & Orchestra in E-Flat Major, Op. 26, J. 109- Clarinet Concertino in C Minor  E-Flat Major, Op. 26, J. 109.mp3", instrument: "clarinet" },
    { title: "Clarinet Concerto No. 7 in E Flat Major (Darmstädter No. 1)- 3. Rondeau", file: "Carl Stamitz, Andreas Ottensamer, Kammerakademie Potsdam - Clarinet Concerto No. 7 in E Flat Major (Darmstädter No. 1)- 3. Rondeau.mp3", instrument: "clarinet" },
    { title: "Premiere Rhapsody, L. 116", file: "Claude Debussy, Julian Bliss, Bradley Moore - Premiere Rhapsody, L. 116.mp3", instrument: "clarinet" },
    { title: "Première rapsodie in B-Flat Major, CD 124, L. 116 (Orchestral Version)", file: "Claude Debussy, Sabine Meyer, Berliner Philharmoniker, Claudio Abbado - Debussy- Première rapsodie in B-Flat Major, CD 124, L. 116 (Orchestral Version).mp3", instrument: "clarinet" },
    { title: "Old Klezmer Band", file: "Colalaila - Old Klezmer Band.mp3", instrument: "clarinet" },
    { title: "Scaramouche for Clarinet and Piano, Op. 165 d- I. Vif", file: "Darius Milhaud, Sebastian Manz, Martin Klett - Scaramouche for Clarinet and Piano, Op. 165 d- I. Vif.mp3", instrument: "clarinet" },
    { title: "Scaramouche for Clarinet and Piano, Op. 165 d- II. Modéré", file: "Darius Milhaud, Sebastian Manz, Martin Klett - Scaramouche for Clarinet and Piano, Op. 165 d- II. Modéré.mp3", instrument: "clarinet" },
    { title: "Scaramouche for Clarinet and Piano, Op. 165 d- III. Brazileira", file: "Darius Milhaud, Sebastian Manz, Martin Klett - Scaramouche for Clarinet and Piano, Op. 165 d- III. Brazileira.mp3", instrument: "clarinet" },
    { title: "Nature Boy", file: "Eden Ahbez, Martin Fröst, Torleif Thedéen, Svante Henryson - Nature Boy (Arr. For clarinet, cello and double bass).mp3", instrument: "clarinet" },
    { title: "Adagio e Tarantella", file: "Ernesto Cavallini, United States Coast Guard Band, Artist Unknown - Adagio e Tarantella.mp3", instrument: "clarinet" },
    { title: "Oblivion", file: "Florent Héau, Marcela Roggeri - Oblivion.mp3", instrument: "clarinet" },
    { title: "Concerto for Recorder, Transverse Flute, Strings and Continuo in E Minor- IV. Presto", file: "Georg Philipp Telemann, Martin Fröst, Royal Stockholm Philharmonic Orchestra - Concerto for Recorder, Transverse Flute, Strings and Continuo in E Minor- IV. Presto.mp3", instrument: "clarinet" },
    { title: "Clarinet Concerto in C Minor, Op. 31- I. Allegro vigoroso", file: "Gerald Finzi, Robert Plane, Royal Northern Sinfonia, Howard Griffiths - Clarinet Concerto in C Minor, Op. 31- I. Allegro vigoroso.mp3", instrument: "clarinet" },
    { title: "Clarinet Concerto in C Minor, Op. 31- II. Adagio, ma senza rigore", file: "Gerald Finzi, Robert Plane, Royal Northern Sinfonia, Howard Griffiths - Clarinet Concerto in C Minor, Op. 31- II. Adagio, ma senza rigore.mp3", instrument: "clarinet" },
    { title: "Clarinet Concerto in C Minor, Op. 31- III. Rondo- Allegro giocoso", file: "Gerald Finzi, Robert Plane, Royal Northern Sinfonia, Howard Griffiths - Clarinet Concerto in C Minor, Op. 31- III. Rondo- Allegro giocoso.mp3", instrument: "clarinet" },
    { title: "Introduction, Theme and Variations for Clarinet and Orchestra in E-Flat Major", file: "Gioachino Rossini, Orpheus Chamber Orchestra - Introduction, Theme and Variations for Clarinet and Orchestra in E-Flat Major - Cadenza- Charles Neidich- Introduzione- Andante (sostenuto).mp3", instrument: "clarinet" },
    { title: "Klezmer Dances", file: "Göran Fröst, Martin Fröst, Australian Chamber Orchestra, Richard Tognetti - Klezmer Dances.mp3", instrument: "clarinet" },
    { title: "Klezmer Dance No. 2", file: "Göran Fröst, Martin Fröst, Royal Stockholm Philharmonic Orchestra - Klezmer Dance No. 2.mp3", instrument: "clarinet" },
    { title: "Chance Dance", file: "Greg Mills, Eric Mandat - Chance Dance.mp3", instrument: "clarinet" },
    { title: "Tag Team", file: "Greg Mills, Eric Mandat - Tag Team.mp3", instrument: "clarinet" },
    { title: "Solo de concours, Op. 10", file: "Henri Rabaud, Michael Collins, Michael McHale - Solo de concours, Op. 10.mp3", instrument: "clarinet" },
    { title: "Ancient Suite", file: "Hildegard von Bingen, Martin Fröst, Adolf Fredriks Flickkör - Ancient Suite.mp3", instrument: "clarinet" },
    { title: "The Tale Of Viktor Navorski - The Terminal", file: "John Williams - The Tale Of Viktor Navorski - The TerminalSoundtrack Version.mp3", instrument: "clarinet" },
    { title: "Sonatina for Clarinet and Piano- I. Allegro con brio", file: "Malcolm Arnold, Ronald Van Spaendonck, Eliane Reyes - Sonatina for Clarinet and Piano- I. Allegro con brio.mp3", instrument: "clarinet" },
    { title: "Nana", file: "Manuel de Falla, Martin Fröst, Royal Stockholm Philharmonic Orchestra - Nana.mp3", instrument: "clarinet" },
    { title: "Duo in E flat, Op. 15", file: "Norbert Burgmüller, Bettina Aust, Robert Aust - Duo in E flat, Op. 15.mp3", instrument: "clarinet" },
    { title: "River of Crystal Light", file: "Peter Lieuwen, Texas Music Festival Orchestra, David Campbell, Franz Anton Krager, Moores School Symphony Orchestra - River of Crystal Light.mp3", instrument: "clarinet" },
    { title: "Souvenir d'un lieu cher, Op. 42- No. 3, Mélodie in E-Flat Major", file: "Pyotr Ilyich Tchaikovsky, Sharon Kam, Itamar Golan - Souvenir d'un lieu cher, Op. 42- No. 3, Mélodie in E-Flat Major.mp3", instrument: "clarinet" },
    { title: "Rolig Pers Polska", file: "Traditional, Martin Fröst, Royal Stockholm Philharmonic Orchestra - Rolig Pers Polska.mp3", instrument: "clarinet" },
    { title: "Rhapsody for Clarinet", file: "Willson Osborne, Karl Leister - Rhapsody for Clarinet.mp3", instrument: "clarinet" },

    // Guitar
    { title: "Falling in Love", file: "Andy Angel - (I Can't Help) Falling in Love - Guitar Version.mp3", instrument: "guitar" },
    { title: "911", file: "Andy Angel - 911 - Acoustic Cover.mp3", instrument: "guitar" },
    { title: "All I Want Is You", file: "Andy Angel - All I Want Is You - Acoustic Cover.mp3", instrument: "guitar" },
    { title: "Are You With Me", file: "Andy Angel - Are You With Me - Guitar Version.mp3", instrument: "guitar" },
    { title: "Bette Davis Eyes", file: "Andy Angel - Bette Davis Eyes - Guitar Version.mp3", instrument: "guitar" },
    { title: "Black Hole Sun", file: "Andy Angel - Black Hole Sun - Guitar Cover.mp3", instrument: "guitar" },
    { title: "Blinding Lights", file: "Andy Angel - Blinding Lights - Guitar Version.mp3", instrument: "guitar" },
    { title: "Circles", file: "Andy Angel - Circles - Guitar Cover.mp3", instrument: "guitar" },
    { title: "Creep", file: "Andy Angel - Creep - Guitar Version.mp3", instrument: "guitar" },
    { title: "Do I Wanna Know", file: "Andy Angel - Do I Wanna Know - Guitar Cover.mp3", instrument: "guitar" },
    { title: "Dreams", file: "Andy Angel - Dreams - Guitar Version.mp3", instrument: "guitar" },
    { title: "Everglow", file: "Andy Angel - Everglow - Guitar Version.mp3", instrument: "guitar" },
    { title: "Every Breath You Take", file: "Andy Angel - Every Breath You Take - Guitar Version.mp3", instrument: "guitar" },
    { title: "Everywhere", file: "Andy Angel - Everywhere - Acoustic Cover.mp3", instrument: "guitar" },
    { title: "Fast Car", file: "Andy Angel - Fast Car - Guitar Cover.mp3", instrument: "guitar" },
    { title: "Free Falling", file: "Andy Angel - Free Falling - Guitar Version.mp3", instrument: "guitar" },
    { title: "Hallelujah", file: "Andy Angel - Hallelujah - Guitar Version.mp3", instrument: "guitar" },
    { title: "Here With Me", file: "Andy Angel - Here With Me - Acoustic Cover.mp3", instrument: "guitar" },
    { title: "Hey Brother", file: "Andy Angel - Hey Brother - Guitar Cover.mp3", instrument: "guitar" },
    { title: "I Can See Clearly Now", file: "Andy Angel - I Can See Clearly Now - Acoustic Cover.mp3", instrument: "guitar" },
    { title: "I Don't Want to Miss a Thing", file: "Andy Angel - I Don't Want to Miss a Thing - Guitar Version.mp3", instrument: "guitar" },
    { title: "It Must Have Been Love", file: "Andy Angel - It Must Have Been Love - Guitar Version.mp3", instrument: "guitar" },
    { title: "Knockin' on Heaven's Door", file: "Andy Angel - Knockin' on Heaven's Door - Acoustic Cover.mp3", instrument: "guitar" },
    { title: "Last Night", file: "Andy Angel - Last Night - Acoustic Cover.mp3", instrument: "guitar" },
    { title: "Layla", file: "Andy Angel - Layla - Acoustic Cover.mp3", instrument: "guitar" },
    { title: "Let Her Go", file: "Andy Angel - Let Her Go - Guitar Version.mp3", instrument: "guitar" },
    { title: "Like a Prayer", file: "Andy Angel - Like a Prayer - Acoustic Cover.mp3", instrument: "guitar" },
    { title: "Livin' On A Prayer", file: "Andy Angel - Livin' On A Prayer - Acoustic Cover.mp3", instrument: "guitar" },
    { title: "Losing My Religion", file: "Andy Angel - Losing My Religion - Guitar Version.mp3", instrument: "guitar" },
    { title: "Love Yourself", file: "Andy Angel - Love Yourself - Guitar Version.mp3", instrument: "guitar" },
    { title: "Personal Jesus", file: "Andy Angel - Personal Jesus - Guitar Cover.mp3", instrument: "guitar" },
    { title: "Poison", file: "Andy Angel - Poison - Guitar Cover.mp3", instrument: "guitar" },
    { title: "Riptide", file: "Andy Angel - Riptide - Guitar Version.mp3", instrument: "guitar" },
    { title: "SNAP", file: "Andy Angel - SNAP - Acoustic Cover.mp3", instrument: "guitar" },
    { title: "Set Fire to the Rain", file: "Andy Angel - Set Fire to the Rain - Guitar Version.mp3", instrument: "guitar" },
    { title: "Shivers", file: "Andy Angel - Shivers - Guitar Version.mp3", instrument: "guitar" },
    { title: "Show Must Go On", file: "Andy Angel - Show Must Go On - Guitar Cover.mp3", instrument: "guitar" },
    { title: "The Sound of Silence", file: "Andy Angel - The Sound of Silence - Guitar Version.mp3", instrument: "guitar" },
    { title: "We're Not Gonna Take It", file: "Andy Angel - We're Not Gonna Take It - Guitar Cover.mp3", instrument: "guitar" },
    { title: "Wild World", file: "Andy Angel - Wild World - Acoustic Cover.mp3", instrument: "guitar" },
    { title: "With Or Without You", file: "Andy Angel - With Or Without You - Guitar Cover.mp3", instrument: "guitar" },
    { title: "Without You", file: "Andy Angel - Without You - Guitar Cover.mp3", instrument: "guitar" },
    { title: "Wonderwall", file: "Andy Angel - Wonderwall - Guitar Version.mp3", instrument: "guitar" },
    { title: "You're Beautiful", file: "Andy Angel - You're Beautiful - Guitar Version.mp3", instrument: "guitar" },
    { title: "Your Song", file: "Andy Angel - Your Song - Guitar Version.mp3", instrument: "guitar" },
    { title: "Impossible", file: "Bourbon Pine - Impossible - Guitar Cover.mp3", instrument: "guitar" },
    { title: "Shallow", file: "Bourbon Pine - Shallow - Guitar Cover.mp3", instrument: "guitar" },
    { title: "Until I Found You", file: "Bourbon Pine - Until I Found You - Guitar Cover.mp3", instrument: "guitar" },
    { title: "Where Are You Now", file: "Bourbon Pine - Where Are You Now - Guitar Cover.mp3", instrument: "guitar" },
    { title: "Angels Like You", file: "JOHANNA - Angels Like You - Guitar Version.mp3", instrument: "guitar" },
    { title: "Be My Mistake", file: "JOHANNA - Be My Mistake - Guitar Version.mp3", instrument: "guitar" },
    { title: "Cruel Summer", file: "JOHANNA - Cruel Summer - Guitar Version.mp3", instrument: "guitar" },
    { title: "Easy On Me", file: "JOHANNA - Easy On Me - Guitar Version.mp3", instrument: "guitar" },
    { title: "Here Comes The Sun", file: "JOHANNA - Here Comes The Sun - Guitar Version.mp3", instrument: "guitar" },
    { title: "I Ain't Worried", file: "JOHANNA - I Ain't Worried - Guitar Version.mp3", instrument: "guitar" },
    { title: "I Feel It Coming", file: "JOHANNA - I Feel It Coming - Guitar Version.mp3", instrument: "guitar" },
    { title: "Let It Go", file: "JOHANNA - Let It Go - Guitar Version.mp3", instrument: "guitar" },
    { title: "Matilda", file: "JOHANNA - Matilda - Guitar Version.mp3", instrument: "guitar" },
    { title: "Paradise", file: "JOHANNA - Paradise - Guitar Version.mp3", instrument: "guitar" },
    { title: "Something Just Like This", file: "JOHANNA - Something Just Like This - Guitar Version.mp3", instrument: "guitar" },
    { title: "Viva La Vida", file: "JOHANNA - Viva La Vida - Guitar Version.mp3", instrument: "guitar" },
    { title: "When We Were Young", file: "JOHANNA - When We Were Young - Guitar Version.mp3", instrument: "guitar" },
    { title: "driver's license", file: "JOHANNA - driver's licence - Guitar Version.mp3", instrument: "guitar" },
    { title: "everything i wanted", file: "JOHANNA - everything i wanted - Guitar Version.mp3", instrument: "guitar" },
    { title: "Baba O'Riley", file: "Johan Kvarnström - Baba O'Riley - Guitar Version.mp3", instrument: "guitar" },
    { title: "Blackbird", file: "Johan Kvarnström - Blackbird - Guitar Cover.mp3", instrument: "guitar" },
    { title: "Cold Water", file: "Johan Kvarnström - Cold Water - Guitar Version.mp3", instrument: "guitar" },
    { title: "Could You Be Loved", file: "Johan Kvarnström - Could You Be Loved - Guitar Version.mp3", instrument: "guitar" },
    { title: "Euphoria", file: "Johan Kvarnström - Euphoria - Guitar Cover.mp3", instrument: "guitar" },
    { title: "Heartbeats", file: "Johan Kvarnström - Heartbeats - Guitar Version.mp3", instrument: "guitar" },
    { title: "Lay All Your Love On Me", file: "Johan Kvarnström - Lay All Your Love On Me - Guitar Version.mp3", instrument: "guitar" },
    { title: "Pumped Up Kicks", file: "Johan Kvarnström - Pumped Up Kicks - Guitar Cover.mp3", instrument: "guitar" },
    { title: "Rolling in the Deep", file: "Johan Kvarnström - Rolling in the Deep - Guitar Cover.mp3", instrument: "guitar" },
    { title: "Say My Name", file: "Johan Kvarnström - Say My Name - Guitar Cover.mp3", instrument: "guitar" },
    { title: "Smoke On the Water", file: "Johan Kvarnström - Smoke On the Water - Guitar Version.mp3", instrument: "guitar" },
    { title: "Stairway to Heaven", file: "Johan Kvarnström - Stairway to Heaven - Guitar Version.mp3", instrument: "guitar" },
    { title: "Summer of '69", file: "Johan Kvarnström - Summer of '69 - Guitar Version.mp3", instrument: "guitar" },
    { title: "Take Me Home, Country Roads", file: "Johan Kvarnström - Take Me Home, Country Roads - Guitar Version.mp3", instrument: "guitar" },
    { title: "Teenage Dirtbag", file: "Johan Kvarnström - Teenage Dirtbag - Guitar Cover.mp3", instrument: "guitar" },
    { title: "good 4 u", file: "Johan Kvarnström - good 4 u - Guitar Version.mp3", instrument: "guitar" },
    { title: "All Night Long", file: "Mount Hayes - All Night Long - Acoustic Cover.mp3", instrument: "guitar" },
    { title: "Another Day in Paradise", file: "Mount Hayes - Another Day in Paradise - Guitar Cover.mp3", instrument: "guitar" },
    { title: "Blue (Da Ba Dee)", file: "Mount Hayes - Blue (Da Ba Dee) - Acoustic Cover.mp3", instrument: "guitar" },
    { title: "Chasing Cars", file: "Mount Hayes - Chasing Cars - Acoustic Version.mp3", instrument: "guitar" },
    { title: "Chemical", file: "Mount Hayes - Chemical - Guitar Cover.mp3", instrument: "guitar" },
    { title: "Congratulations", file: "Mount Hayes - Congratulations - Guitar Cover.mp3", instrument: "guitar" },
    { title: "Crosses", file: "Mount Hayes - Crosses - Guitar Cover.mp3", instrument: "guitar" },
    { title: "Everlong", file: "Mount Hayes - Everlong - Guitar Version.mp3", instrument: "guitar" },
    { title: "Flowers", file: "Mount Hayes - Flowers - Acoustic Cover.mp3", instrument: "guitar" },
    { title: "Heaven", file: "Mount Hayes - Heaven - Acoustic Cover.mp3", instrument: "guitar" },
    { title: "Hold On, We're Going Home", file: "Mount Hayes - Hold On, We're Going Home - Acoustic Cover.mp3", instrument: "guitar" },
    { title: "I Can't Feel My Face", file: "Mount Hayes - I Can't Feel My Face - Acoustic Cover.mp3", instrument: "guitar" },
    { title: "I'm On Fire", file: "Mount Hayes - I'm On Fire - Acoustic Cover.mp3", instrument: "guitar" },
    { title: "I'm Yours", file: "Mount Hayes - I'm Yours - Guitar Version.mp3", instrument: "guitar" },
    { title: "Into You", file: "Mount Hayes - Into You - Acoustic Cover.mp3", instrument: "guitar" },
    { title: "Isn't She Lovely", file: "Mount Hayes - Isn't She Lovely - Acoustic Version.mp3", instrument: "guitar" },
    { title: "Lose You to Love Me", file: "Mount Hayes - Lose You to Love Me - Acoustic Cover.mp3", instrument: "guitar" },
    { title: "Mad World", file: "Mount Hayes - Mad World - Guitar Cover.mp3", instrument: "guitar" },
    { title: "Magic", file: "Mount Hayes - Magic - Guitar Cover.mp3", instrument: "guitar" },
    { title: "Numb", file: "Mount Hayes - Numb - Guitar Cover.mp3", instrument: "guitar" },
    { title: "One Last Time", file: "Mount Hayes - One Last Time - Guitar Cover.mp3", instrument: "guitar" },
    { title: "Purple Rain", file: "Mount Hayes - Purple Rain - Guitar Cover.mp3", instrument: "guitar" },
    { title: "Ring of Fire", file: "Mount Hayes - Ring of Fire - Guitar Cover.mp3", instrument: "guitar" },
    { title: "STAY", file: "Mount Hayes - STAY - Acoustic Version.mp3", instrument: "guitar" },
    { title: "Say You Wont Let Go", file: "Mount Hayes - Say You Wont Let Go - Acoustic Version.mp3", instrument: "guitar" },
    { title: "Scar Tissue", file: "Mount Hayes - Scar Tissue - Guitar Version.mp3", instrument: "guitar" },
    { title: "Señorita", file: "Mount Hayes - Señorita - Acoustic Guitar Version.mp3", instrument: "guitar" },
    { title: "Sex on Fire", file: "Mount Hayes - Sex on Fire - Guitar Version.mp3", instrument: "guitar" },
    { title: "Skinny Love", file: "Mount Hayes - Skinny Love - Guitar Version.mp3", instrument: "guitar" },
    { title: "Snow (Hey Ho)", file: "Mount Hayes - Snow (Hey Ho) - Acoustic Version.mp3", instrument: "guitar" },
    { title: "Sorry", file: "Mount Hayes - Sorry - Guitar Version.mp3", instrument: "guitar" },
    { title: "Still Haven't Found What I'm Looking For", file: "Mount Hayes - Still Haven't Found What I'm Looking For - Guitar Version.mp3", instrument: "guitar" },
    { title: "Style", file: "Mount Hayes - Style - Guitar Cover.mp3", instrument: "guitar" },
    { title: "Sweet Child o' Mine", file: "Mount Hayes - Sweet Child o' Mine - Acoustic Guitar Version.mp3", instrument: "guitar" },
    { title: "Sweet Home Alabama", file: "Mount Hayes - Sweet Home Alabama - Acoustic Version.mp3", instrument: "guitar" },
    { title: "Teenage Dream", file: "Mount Hayes - Teenage Dream - Guitar Cover.mp3", instrument: "guitar" },
    { title: "Thinking Out Loud", file: "Mount Hayes - Thinking Out Loud - Acoustic Version.mp3", instrument: "guitar" },
    { title: "Time After Time", file: "Mount Hayes - Time After Time - Guitar Cover.mp3", instrument: "guitar" },
    { title: "Under the Bridge", file: "Mount Hayes - Under the Bridge - Guitar Version.mp3", instrument: "guitar" },
    { title: "Use Somebody", file: "Mount Hayes - Use Somebody - Acoustic Guitar Version.mp3", instrument: "guitar" },
    { title: "Watermelon Sugar", file: "Mount Hayes - Watermelon Sugar - Acoustic Version.mp3", instrument: "guitar" },
    { title: "Yellow", file: "Mount Hayes - Yellow - Acoustic Guitar Version.mp3", instrument: "guitar" },
    { title: "Zombie", file: "Mount Hayes - Zombie - Acoustic Version.mp3", instrument: "guitar" },
    { title: "a thousand years", file: "guitar girl - a thousand years - guitar version.mp3", instrument: "guitar" },
    { title: "always you", file: "guitar girl - always you - guitar version.mp3", instrument: "guitar" },
    { title: "arcade", file: "guitar girl - arcade - guitar version.mp3", instrument: "guitar" },
    { title: "at my worst", file: "guitar girl - at my worst - guitar version.mp3", instrument: "guitar" },
    { title: "better", file: "guitar girl - better - guitar version.mp3", instrument: "guitar" },
    { title: "build me up buttercup", file: "guitar girl - build me up buttercup - guitar version.mp3", instrument: "guitar" },
    { title: "butter", file: "guitar girl - butter - guitar version.mp3", instrument: "guitar" },
    { title: "chasing cars", file: "guitar girl - chasing cars - guitar version.mp3", instrument: "guitar" },
    { title: "coffee", file: "guitar girl - coffee - guitar version.mp3", instrument: "guitar" },
    { title: "corduroy dreams", file: "guitar girl - corduroy dreams - guitar version.mp3", instrument: "guitar" },
    { title: "counting stars", file: "guitar girl - counting stars - guitar version.mp3", instrument: "guitar" },
    { title: "dandelions", file: "guitar girl - dandelions - guitar version.mp3", instrument: "guitar" },
    { title: "dark horse", file: "guitar girl - dark horse - guitar version.mp3", instrument: "guitar" },
    { title: "demons", file: "guitar girl - demons - guitar version.mp3", instrument: "guitar" },
    { title: "ditto", file: "guitar girl - ditto - guitar version.mp3", instrument: "guitar" },
    { title: "double take", file: "guitar girl - double take - guitar version.mp3", instrument: "guitar" },
    { title: "eenie meenie", file: "guitar girl - eenie meenie - guitar version.mp3", instrument: "guitar" },
    { title: "everything i wanted", file: "guitar girl - everything i wanted - guitar version.mp3", instrument: "guitar" },
    { title: "eyes blue like the atlantic", file: "guitar girl - eyes blue like the atlantic - guitar version.mp3", instrument: "guitar" },
    { title: "glimpse of us", file: "guitar girl - glimpse of us - guitar version.mp3", instrument: "guitar" },
    { title: "heather", file: "guitar girl - heather - guitar version.mp3", instrument: "guitar" },
    { title: "here with me", file: "guitar girl - here with me - guitar version.mp3", instrument: "guitar" },
    { title: "hey, soul sister", file: "guitar girl - hey, soul sister - guitar version.mp3", instrument: "guitar" },
    { title: "i.f.l.y.", file: "guitar girl - i.f.l.y. - guitar version.mp3", instrument: "guitar" },
    { title: "ice cream", file: "guitar girl - ice cream - guitar version.mp3", instrument: "guitar" },
    { title: "imagination", file: "guitar girl - imagination - guitar version.mp3", instrument: "guitar" },
    { title: "it will rain", file: "guitar girl - it will rain - guitar version.mp3", instrument: "guitar" },
    { title: "jocelyn flores", file: "guitar girl - jocelyn flores - guitar version.mp3", instrument: "guitar" },
    { title: "just the two of us", file: "guitar girl - just the two of us - guitar version.mp3", instrument: "guitar" },
    { title: "kiss me more", file: "guitar girl - kiss me more - guitar version.mp3", instrument: "guitar" },
    { title: "last christmas", file: "guitar girl - last christmas - guitar version.mp3", instrument: "guitar" },
    { title: "like i can", file: "guitar girl - like i can - guitar version.mp3", instrument: "guitar" },
    { title: "line without a hook", file: "guitar girl - line without a hook - guitar version.mp3", instrument: "guitar" },
    { title: "love is gone", file: "guitar girl - love is gone - guitar version.mp3", instrument: "guitar" },
    { title: "mad at disney", file: "guitar girl - mad at disney - guitar version.mp3", instrument: "guitar" },
    { title: "mockingbird", file: "guitar girl - mockingbird - guitar version.mp3", instrument: "guitar" },
    { title: "my boo", file: "guitar girl - my boo - guitar version.mp3", instrument: "guitar" },
    { title: "my love mine all mine", file: "guitar girl - my love mine all mine - guitar version.mp3", instrument: "guitar" },
    { title: "night changes", file: "guitar girl - night changes - guitar version.mp3", instrument: "guitar" },
    { title: "ocean eyes", file: "guitar girl - ocean eyes - guitar version.mp3", instrument: "guitar" },
    { title: "polaroid love", file: "guitar girl - polaroid love - guitar version.mp3", instrument: "guitar" },
    { title: "pompeii", file: "guitar girl - pompeii - guitar version.mp3", instrument: "guitar" },
    { title: "rewrite the stars", file: "guitar girl - rewrite the stars - guitar version.mp3", instrument: "guitar" },
    { title: "save your tears", file: "guitar girl - save your tears - guitar version.mp3", instrument: "guitar" },
    { title: "slow dancing in the dark", file: "guitar girl - slow dancing in the dark - guitar version.mp3", instrument: "guitar" },
    { title: "stay with me", file: "guitar girl - stay with me - guitar version.mp3", instrument: "guitar" },
    { title: "stereo hearts", file: "guitar girl - stereo hearts - guitar version.mp3", instrument: "guitar" },
    { title: "still into you", file: "guitar girl - still into you - guitar version.mp3", instrument: "guitar" },
    { title: "still with you", file: "guitar girl - still with you - guitar version.mp3", instrument: "guitar" },
    { title: "sweet home alabama", file: "guitar girl - sweet home alabama - guitar version.mp3", instrument: "guitar" },
    { title: "take me to church", file: "guitar girl - take me to church - guitar version.mp3", instrument: "guitar" },
    { title: "talking to the moon", file: "guitar girl - talking to the moon - guitar version.mp3", instrument: "guitar" },
    { title: "the remedy for a broken heart (why am i so in love)", file: "guitar girl - the remedy for a broken heart (why am i so in love) - guitar version.mp3", instrument: "guitar" },
    { title: "the scientist", file: "guitar girl - the scientist - guitar version.mp3", instrument: "guitar" },
    { title: "to the bone", file: "guitar girl - to the bone - guitar version.mp3", instrument: "guitar" },
    { title: "tonight you belong to me", file: "guitar girl - tonight you belong to me - guitar version.mp3", instrument: "guitar" },
    { title: "until i found you", file: "guitar girl - until i found you - guitar version.mp3", instrument: "guitar" },

    // Harp
    { title: "Norwegian Lullaby", file: "Harper Tasche - Norwegian Lullaby.mp3", instrument: "harp" },

    // Piano
    { title: "Ellie", file: "Aeyes Libe - Ellie.mp3", instrument: "piano" },
    { title: "Once", file: "Alexis Ffrench - Once.mp3", instrument: "piano" },
    { title: "land in sight", file: "Alfons Daiminger - land in sight.mp3", instrument: "piano" },
    { title: "Full Bloom", file: "Allysium - Full Bloom.mp3", instrument: "piano" },
    { title: "This Tender Appeal", file: "Allysium - This Tender Appeal.mp3", instrument: "piano" },
    { title: "Forevermore", file: "Ambrosiae - Forevermore.mp3", instrument: "piano" },
    { title: "Cascade", file: "André Dívou - Cascade.mp3", instrument: "piano" },
    { title: "Before You", file: "Andrea Prine - Before You.mp3", instrument: "piano" },
    { title: "Pine Scent", file: "Anthony Sullivan - Pine Scent.mp3", instrument: "piano" },
    { title: "Miles and Miles", file: "Antoine Di Luzio - Miles and Miles.mp3", instrument: "piano" },
    { title: "The Story of Forever", file: "Aquilegia - The Story of Forever.mp3", instrument: "piano" },
    { title: "A Safe Space", file: "Aramis Morel - A Safe Space.mp3", instrument: "piano" },
    { title: "Endlich", file: "Arata Rin - Endlich.mp3", instrument: "piano" },
    { title: "Diaphanous", file: "Arden Brooks - Diaphanous.mp3", instrument: "piano" },
    { title: "Afterlight", file: "Arlo Thiem - Afterlight.mp3", instrument: "piano" },
    { title: "The Swan", file: "Ava Cerasoli - The swan.mp3", instrument: "piano" },
    { title: "Morning Dew", file: "Blue George - Morning Dew.mp3", instrument: "piano" },
    { title: "Fiume", file: "Carluccio - Fiume.mp3", instrument: "piano" },
    { title: "A quiet river", file: "Christian Janssen - A quiet river.mp3", instrument: "piano" },
    { title: "Hearts of Desire", file: "Cole Neumann - Hearts of Desire.mp3", instrument: "piano" },
    { title: "Archipelago", file: "Damien Jeunet - Archipelago.mp3", instrument: "piano" },
    { title: "In Presence", file: "Dean Demir - In Presence.mp3", instrument: "piano" },
    { title: "Wish", file: "Domi Nova - Wish.mp3", instrument: "piano" },
    { title: "Solace", file: "Dunham Froebel - Solace.mp3", instrument: "piano" },
    { title: "Window Seat", file: "Dwight Rivera - Window Seat.mp3", instrument: "piano" },
    { title: "Lazy Sunday Vibes", file: "Erjos - Lazy Sunday Vibes.mp3", instrument: "piano" },
    { title: "Valse Naturelle", file: "Etienne Balestre - Valse Naturelle.mp3", instrument: "piano" },
    { title: "Fjord", file: "Eyøni - Fjord.mp3", instrument: "piano" },
    { title: "Fino Mornasco", file: "Fabrizio Gallo - Fino Mornasco.mp3", instrument: "piano" },
    { title: "Waitings", file: "Felix Tanguy - Waitings.mp3", instrument: "piano" },
    { title: "A New Start", file: "Ferragno - A New Start.mp3", instrument: "piano" },
    { title: "Notturno", file: "Finja Seiden - Notturno.mp3", instrument: "piano" },
    { title: "Desire paths", file: "Finn Lenoir - Desire paths.mp3", instrument: "piano" },
    { title: "Seasons Flowing", file: "Fleur Bloom - Seasons Flowing.mp3", instrument: "piano" },
    { title: "Almost April", file: "Florentin Davies - Almost April.mp3", instrument: "piano" },
    { title: "Eridani", file: "Flori Vivea - Eridani.mp3", instrument: "piano" },
    { title: "Nostalgia", file: "Floyd Nova - Nostalgia.mp3", instrument: "piano" },
    { title: "Sanctuary", file: "Floyd Nova - Sanctuary.mp3", instrument: "piano" },
    { title: "Contemplazione del Mare", file: "Gianni Domenici - Contemplazione del Mare.mp3", instrument: "piano" },
    { title: "For Asher", file: "Glenn Natale - For Asher.mp3", instrument: "piano" },
    { title: "For A Moment", file: "Haley Morrison - For A Moment.mp3", instrument: "piano" },
    { title: "The Proposal", file: "Henriette Fleich - The Proposal.mp3", instrument: "piano" },
    { title: "190306-11", file: "Hideyuki Hashimoto - 190306-11.mp3", instrument: "piano" },
    { title: "Like an Open Book", file: "Hudson Rull - Like an Open Book.mp3", instrument: "piano" },
    { title: "Grand Canyon", file: "Ivan Vladusic - Grand Canyon.mp3", instrument: "piano" },
    { title: "soft life", file: "Jack Ame - soft life.mp3", instrument: "piano" },
    { title: "The Coming Day", file: "Jack Pelayo - The Coming Day.mp3", instrument: "piano" },
    { title: "Glance Out A Casement Window", file: "Janet Redger - Glance Out A Casement Window.mp3", instrument: "piano" },
    { title: "Under a tree", file: "Janet Redger - Under a tree.mp3", instrument: "piano" },
    { title: "Countryside Mansion", file: "Joanne Gardiner - Countryside Mansion.mp3", instrument: "piano" },
    { title: "Where the Rivers Run", file: "Joaquim Azevedo - Where the Rivers Run.mp3", instrument: "piano" },
    { title: "Peace flow", file: "Jon Albreit - Peace flow.mp3", instrument: "piano" },
    { title: "Biassono", file: "Joviano Carrera - Biassono.mp3", instrument: "piano" },
    { title: "Elegie", file: "Kiara Leonard - Elegie.mp3", instrument: "piano" },
    { title: "Come close", file: "Korey Banks - Come close.mp3", instrument: "piano" },
    { title: "Dalmine", file: "Lakes of Lagan - Dalmine.mp3", instrument: "piano" },
    { title: "Future 未来", file: "Li Zemin - Future 未来.mp3", instrument: "piano" },
    { title: "Bona Fide", file: "Linn Hope - Bona Fide.mp3", instrument: "piano" },
    { title: "to be better again", file: "Lonesome Mind - to be better again.mp3", instrument: "piano" },
    { title: "Arabesco", file: "Lorenzo Fiore - Arabesco.mp3", instrument: "piano" },
    { title: "Adieux", file: "Ludovico Einaudi - Adieux.mp3", instrument: "piano" },
    { title: "A tale to tell", file: "Luiza Schmidt - A tale to tell.mp3", instrument: "piano" },
    { title: "I Believe", file: "M. Ljungström - I Believe.mp3", instrument: "piano" },
    { title: "Quietly Into The Night", file: "M. Ljungström - Quietly Into The Night.mp3", instrument: "piano" },
    { title: "Sound Of Mind", file: "Macan Moreira - Sound Of Mind.mp3", instrument: "piano" },
    { title: "Nordanvind", file: "Malmkvist - Nordanvind.mp3", instrument: "piano" },
    { title: "Falling Rain", file: "Matthew L. Fisher - Falling Rain.mp3", instrument: "piano" },
    { title: "Schutter", file: "May Laude - Schutter.mp3", instrument: "piano" },
    { title: "floating points", file: "May Laude - floating points.mp3", instrument: "piano" },
    { title: "Fall a hundred times", file: "Maya Sarfatto - Fall a hundred times.mp3", instrument: "piano" },
    { title: "Humanity", file: "Melanié Poret - Humanity.mp3", instrument: "piano" },
    { title: "Nouveau Départ", file: "Mes Croquis - Nouveau Départ.mp3", instrument: "piano" },
    { title: "Veiled Remembrance", file: "Mijongya - Veiled Remembrance.mp3", instrument: "piano" },
    { title: "Inmaterial color", file: "Mima Renard - Inmaterial color.mp3", instrument: "piano" },
    { title: "I Dare Not Dream- Fantasia on a Theme", file: "Mírabilis - I Dare Not Dream- Fantasia on a Theme.mp3", instrument: "piano" },
    { title: "Misterbianco", file: "Mireia Lluna - Misterbianco.mp3", instrument: "piano" },
    { title: "Luminous", file: "Moldoveanu - Luminous.mp3", instrument: "piano" },
    { title: "between the mountains", file: "Nadav Cohen - between the mountains.mp3", instrument: "piano" },
    { title: "Beauty", file: "Nascondiglio - Beauty.mp3", instrument: "piano" },
    { title: "Prato Di Girasoli", file: "Nascondiglio - Prato Di Girasoli.mp3", instrument: "piano" },
    { title: "Valse Delle Vigne", file: "Nascondiglio - Valse Delle Vigne.mp3", instrument: "piano" },
    { title: "Beginnings", file: "Néer - Beginnings.mp3", instrument: "piano" },
    { title: "Mavro", file: "Niamh Shona - Mavro.mp3", instrument: "piano" },
    { title: "Daydreamer", file: "Noah Hart - Daydreamer.mp3", instrument: "piano" },
    { title: "Dreamt, far hope", file: "North Connolly - Dreamt, far hope....mp3", instrument: "piano" },
    { title: "Whispering Oaks", file: "Olivier DeGrasse - Whispering Oaks.mp3", instrument: "piano" },
    { title: "My Story", file: "Portia Price - My Story.mp3", instrument: "piano" },
    { title: "Fields Of Love", file: "Reinhard Krause - Fields Of Love.mp3", instrument: "piano" },
    { title: "Onward", file: "Remi Sinclair - Onward.mp3", instrument: "piano" },
    { title: "Aspres", file: "Ren Lockhart - Aspres.mp3", instrument: "piano" },
    { title: "Cataverdis", file: "Ren Lockhart - Cataverdis.mp3", instrument: "piano" },
    { title: "Spring Roses", file: "Ren Lockhart - Spring Roses.mp3", instrument: "piano" },
    { title: "Almenno San Salvatore", file: "Rhian Cadogan - Almenno San Salvatore.mp3", instrument: "piano" },
    { title: "The Breeze and The Wildflower", file: "Roasting Coffee Beans - The Breeze and The Wildflower.mp3", instrument: "piano" },
    { title: "Grounded in Love", file: "Rocco - Grounded in Love.mp3", instrument: "piano" },
    { title: "Muse Of History", file: "Roland Toubin - Muse Of History.mp3", instrument: "piano" },
    { title: "To Bring Rest", file: "Sabrina Austin - To Bring Rest.mp3", instrument: "piano" },
    { title: "Arbor", file: "Samuel Kees - Arbor.mp3", instrument: "piano" },
    { title: "The Old Garden", file: "Sanna Aalto - The Old Garden.mp3", instrument: "piano" },
    { title: "Cavaria", file: "Shea Ada - Cavaria.mp3", instrument: "piano" },
    { title: "Paths", file: "Silje Mørk - Paths.mp3", instrument: "piano" },
    { title: "Astray", file: "Simon Vouet - Astray.mp3", instrument: "piano" },
    { title: "Sketch of an Oak", file: "Stanley Lloyd - Sketch of an Oak.mp3", instrument: "piano" },
    { title: "Communion", file: "Stephan Moccio - Communion.mp3", instrument: "piano" },
    { title: "Dancing Dreams", file: "Steven Windhaug - Dancing Dreams.mp3", instrument: "piano" },
    { title: "Deja", file: "Taganema - Deja.mp3", instrument: "piano" },
    { title: "Moving on", file: "Tankeflukt - Moving on.mp3", instrument: "piano" },
    { title: "Just Stay", file: "Tristaan Wilkes - Just Stay.mp3", instrument: "piano" },
    { title: "Elegy Of Solace", file: "Una Luna - Elegy Of Solace.mp3", instrument: "piano" },
    { title: "To New Beginnings", file: "Una Luna - To New Beginnings.mp3", instrument: "piano" },
    { title: "Resta Con Me", file: "Valentina Romano - Resta Con Me.mp3", instrument: "piano" },
    { title: "Other Side of The Moon", file: "Valérie Valérie - Other Side of The Moon.mp3", instrument: "piano" },
    { title: "Brume Matinale", file: "Valter Soll - Brume Matinale.mp3", instrument: "piano" },
    { title: "Autumn Sky", file: "Vincent Fanguro - Autumn Sky.mp3", instrument: "piano" },
    { title: "The Way Home", file: "Wendie Solomon - The Way Home.mp3", instrument: "piano" },
    { title: "Serene", file: "Will Kaufman - Serene.mp3", instrument: "piano" },
    { title: "Air from Air", file: "Yasuo Zen - Air from Air.mp3", instrument: "piano" },
    { title: "frozen kiss", file: "everall - frozen kiss.mp3", instrument: "piano" },
    { title: "nocturnal summer", file: "forever day - nocturnal summer.mp3", instrument: "piano" },

    // Saxophone
    { title: "Can't Catch Me Now", file: "Avromi Basch - Can't Catch Me Now - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Cruel Summer", file: "Avromi Basch - Cruel Summer - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Greedy", file: "Avromi Basch - Greedy - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Houdini", file: "Avromi Basch - Houdini - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Imagine", file: "Avromi Basch - Imagine - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Levitating", file: "Avromi Basch - Levitating - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Lipstick", file: "Avromi Basch - Lipstick - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Selfish", file: "Avromi Basch - Selfish - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Stand By Me", file: "Avromi Basch - Stand By Me - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Texas Hold 'Em", file: "Avromi Basch - Texas Hold 'Em - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Training Season", file: "Avromi Basch - Training Season - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "A Little Bit Yours", file: "Bobby G - A Little Bit Yours - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "A Thousand Miles", file: "Bobby G - A Thousand Miles - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Always Be My Baby", file: "Bobby G - Always Be My Baby - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Anyone", file: "Bobby G - Anyone.mp3", instrument: "saxophone" },
    { title: "Back To December", file: "Bobby G - Back To December - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Bad Day", file: "Bobby G - Bad Day - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Better Together", file: "Bobby G - Better Together - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Catch My Breath", file: "Bobby G - Catch My Breath - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Curtains", file: "Bobby G - Curtains - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Daughters", file: "Bobby G - Daughters - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Dive", file: "Bobby G - Dive - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Dreaming with a Broken Heart", file: "Bobby G - Dreaming with a Broken Heart - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Enchanted", file: "Bobby G - Enchanted - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Fearless", file: "Bobby G - Fearless - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Fireflies", file: "Bobby G - Fireflies - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Firework", file: "Bobby G - Firework - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Flowers", file: "Bobby G - Flowers - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Forget Me", file: "Bobby G - Forget Me - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Good Riddance (Time of Your Life)", file: "Bobby G - Good Riddance (Time of Your Life) - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Havana", file: "Bobby G - Havana - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Hey There Delilah", file: "Bobby G - Hey There Delilah - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "I Knew You Were Trouble", file: "Bobby G - I Knew You Were Trouble. - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "I Want It That Way", file: "Bobby G - I Want It That Way - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "I Will Follow You into the Dark", file: "Bobby G - I Will Follow You into the Dark - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "I'll Be Waiting", file: "Bobby G - I'll Be Waiting - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "I'll Make Love To You", file: "Bobby G - I'll Make Love To You - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "If I Ain't Got You", file: "Bobby G - If I Ain't Got You - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "It Wasn't Me", file: "Bobby G - It Wasn't Me - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Just the Way You Are", file: "Bobby G - Just the Way You Are - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Love On The Brain", file: "Bobby G - Love On The Brain - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Material Girl", file: "Bobby G - Material Girl - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Meltdown", file: "Bobby G - Meltdown - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Mercy", file: "Bobby G - Mercy - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "My Love Mine All Mine", file: "Bobby G - My Love Mine All Mine - Saxophone Instrumental.mp3", instrument: "saxophone" },
    { title: "Need You Now", file: "Bobby G - Need You Now - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "No Scrubs", file: "Bobby G - No Scrubs - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Oops!...I Did It Again", file: "Bobby G - Oops!...I Did It Again - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Over My Head", file: "Bobby G - Over My Head - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Perfect", file: "Bobby G - Perfect - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Perfectly Imperfect", file: "Bobby G - Perfectly Imperfect - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Rainbow", file: "Bobby G - Rainbow - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Someone You Loved", file: "Bobby G - Someone You Loved - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Stand By Me", file: "Bobby G - Stand By Me - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Stick Season", file: "Bobby G - Stick Season - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Toxic", file: "Bobby G - Toxic - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Waterfalls", file: "Bobby G - Waterfalls - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "What Was I Made For", file: "Bobby G - What Was I Made For - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "When You Look Me In The Eyes", file: "Bobby G - When You Look Me In The Eyes - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Wildest Dreams", file: "Bobby G - Wildest Dreams - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Wish You The Best", file: "Bobby G - Wish You The Best - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Wonderwall", file: "Bobby G - Wonderwall - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "You Found Me", file: "Bobby G - You Found Me - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "ceilings", file: "Bobby G - ceilings - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "drivers license", file: "Bobby G - drivers license.mp3", instrument: "saxophone" },
    { title: "favorite crime", file: "Bobby G - favorite crime - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "logical", file: "Bobby G - logical - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Chemical", file: "Bobby G, Brendan Ross - Chemical - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Snooze", file: "Bobby G, Evan Jacobson - Snooze - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Used To Be Young", file: "Edward Ong, Bobby G - Used To Be Young - Saxophone and Guitar Instrumental.mp3", instrument: "saxophone" },
    { title: "Fix You", file: "Milo Grande - Fix You - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "See You Again", file: "Milo Grande - See You Again - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Thinking out Loud", file: "Milo Grande - Thinking out Loud - Saxophone Version.mp3", instrument: "saxophone" },
    { title: "Every Breath You Take", file: "Saxophone Rufus - Every Breath You Take.mp3", instrument: "saxophone" },
    { title: "Love Never Felt So Good", file: "Saxophone Rufus - Love Never Felt So Good.mp3", instrument: "saxophone" },

    // Violin
    { title: "All Of Me", file: "Alison Sparrow - All Of Me Violin Cover.mp3", instrument: "violin" },
    { title: "Halo", file: "Caleb Chan, Brian Chan - Halo.mp3", instrument: "violin" },
    { title: "Nobody Gets Me", file: "Caleb Chan, Brian Chan - Nobody Gets Me.mp3", instrument: "violin" },
    { title: "Run the World", file: "Caleb Chan, Brian Chan - Run the World.mp3", instrument: "violin" },
    { title: "Viva La Vida", file: "David Garrett - Viva La Vida.mp3", instrument: "violin" },
    { title: "What About Us", file: "Duomo - What About Us.mp3", instrument: "violin" },
    { title: "Wildest Dreams", file: "Duomo - Wildest Dreams.mp3", instrument: "violin" },
    { title: "You Oughta Know", file: "Duomo, Tomás Peire-Serrate - You Oughta Know.mp3", instrument: "violin" },
    { title: "As It Was", file: "Ground Zero Academy Orchestra - As It Was.mp3", instrument: "violin" },
    { title: "Bloody Mary", file: "Ground Zero Academy Orchestra - Bloody Mary.mp3", instrument: "violin" },
    { title: "Concerning Hobbits", file: "Ground Zero Academy Orchestra - Concerning Hobbits.mp3", instrument: "violin" },
    { title: "Daylight", file: "Ground Zero Academy Orchestra - Daylight.mp3", instrument: "violin" },
    { title: "Demons", file: "Ground Zero Academy Orchestra - Demons.mp3", instrument: "violin" },
    { title: "Flowers", file: "Ground Zero Academy Orchestra - Flowers.mp3", instrument: "violin" },
    { title: "Golden Hour", file: "Ground Zero Academy Orchestra - Golden Hour.mp3", instrument: "violin" },
    { title: "Lift Me Up", file: "Ground Zero Academy Orchestra - Lift Me Up.mp3", instrument: "violin" },
    { title: "Memories", file: "Ground Zero Academy Orchestra - Memories.mp3", instrument: "violin" },
    { title: "O Holy Night", file: "Ground Zero Academy Orchestra - O Holy Night.mp3", instrument: "violin" },
    { title: "Perfect", file: "Ground Zero Academy Orchestra - Perfect.mp3", instrument: "violin" },
    { title: "Running Up That Hill", file: "Ground Zero Academy Orchestra - Running Up That Hill.mp3", instrument: "violin" },
    { title: "Unholy", file: "Ground Zero Academy Orchestra - Unholy.mp3", instrument: "violin" },
    { title: "Yellow", file: "Ground Zero Academy Orchestra - Yellow.mp3", instrument: "violin" },
    { title: "Diamonds", file: "Hannah V, Joe Rodwell - Diamonds.mp3", instrument: "violin" },
    { title: "Arcade", file: "ItsAMoney - Arcade - Violin Version.mp3", instrument: "violin" },
    { title: "Lovely", file: "ItsAMoney - Lovely.mp3", instrument: "violin" },
    { title: "Perfect", file: "Karolina Protsenko - Perfect.mp3", instrument: "violin" },
    { title: "Rockabye", file: "Karolina Protsenko - Rockabye.mp3", instrument: "violin" },
    { title: "Bad Guy", file: "Kezia Amelia - Bad Guy.mp3", instrument: "violin" },
    { title: "Material Girl", file: "Kris Bowers - Material Girl.mp3", instrument: "violin" },
    { title: "Strange", file: "Kris Bowers - Strange (feat. Hillary Smith).mp3", instrument: "violin" },
    { title: "A Feeling I've Never Been", file: "Kris Bowers, Tayla Parx - A Feeling I've Never Been.mp3", instrument: "violin" },
    { title: "Wrecking Ball", file: "Midnite String Quartet - Wrecking Ball.mp3", instrument: "violin" },
    { title: "Deja Vu", file: "Mike Froudarakis, Alexander Leeming Froudakis - Deja Vu.mp3", instrument: "violin" },
    { title: "Havana", file: "Robert Mendoza - Havana.mp3", instrument: "violin" },
    { title: "Sign of the Times", file: "Steve Horner - Sign of the Times - Stripped.mp3", instrument: "violin" },
    { title: "Anti-Hero", file: "Vitamin String Quartet - Anti-Hero.mp3", instrument: "violin" },
    { title: "As It Was", file: "Vitamin String Quartet - As It Was.mp3", instrument: "violin" },
    { title: "Blinding Lights", file: "Vitamin String Quartet - Blinding Lights.mp3", instrument: "violin" },
    { title: "Butter", file: "Vitamin String Quartet - Butter.mp3", instrument: "violin" },
    { title: "Chandelier", file: "Vitamin String Quartet - Chandelier.mp3", instrument: "violin" },
    { title: "Dancing On My Own", file: "Vitamin String Quartet - Dancing On My Own.mp3", instrument: "violin" },
    { title: "Don’t Start Now", file: "Vitamin String Quartet - Don’t Start Now.mp3", instrument: "violin" },
    { title: "Easy On Me", file: "Vitamin String Quartet - Easy On Me.mp3", instrument: "violin" },
    { title: "Girls Like You", file: "Vitamin String Quartet - Girls Like You.mp3", instrument: "violin" },
    { title: "I Will Always Love You", file: "Vitamin String Quartet - I Will Always Love You.mp3", instrument: "violin" },
    { title: "If I Ain't Got You", file: "Vitamin String Quartet - If I Ain't Got You.mp3", instrument: "violin" },
    { title: "In My Blood", file: "Vitamin String Quartet - In My Blood.mp3", instrument: "violin" },
    { title: "Kiss Me More", file: "Vitamin String Quartet - Kiss Me More.mp3", instrument: "violin" },
    { title: "Levitating", file: "Vitamin String Quartet - Levitating.mp3", instrument: "violin" },
    { title: "Peaches", file: "Vitamin String Quartet - Peaches.mp3", instrument: "violin" },
    { title: "Rain On Me", file: "Vitamin String Quartet - Rain On Me.mp3", instrument: "violin" },
    { title: "Running Up That Hill (A Deal With God)", file: "Vitamin String Quartet - Running Up That Hill (A Deal With God).mp3", instrument: "violin" },
    { title: "Santa Tell Me", file: "Vitamin String Quartet - Santa Tell Me.mp3", instrument: "violin" },
    { title: "Stay Away", file: "Vitamin String Quartet - Stay Away.mp3", instrument: "violin" },
    { title: "Stay with Me", file: "Vitamin String Quartet - Stay with Me.mp3", instrument: "violin" },
    { title: "Watermelon Sugar", file: "Vitamin String Quartet - Watermelon Sugar.mp3", instrument: "violin" },
    { title: "bad guy", file: "Vitamin String Quartet - bad guy.mp3", instrument: "violin" },
    { title: "driver's license", file: "Vitamin String Quartet - driver's license.mp3", instrument: "violin" },
    { title: "positions", file: "Vitamin String Quartet - positions - Bonus Track.mp3", instrument: "violin" },
    { title: "thank u, next", file: "Vitamin String Quartet - thank u, next.mp3", instrument: "violin" }
];

export default songList;
